#!/usr/local/bin/php
<?php
$port = 9501;
$address = "127.0.0.1";
$ssock;
$csock;
$uin;
$redisMain = new Redis();
$redisMain->connect('127.0.0.1',6379);

$pids = [];
$ssock = stream_socket_server("tcp://$address:$port");
echo "Waiting for client...\n";
while ($csock = stream_socket_accept($ssock,300)) {
  echo "new client".$csock,"\n";
  $redisMain->lpush('conn',$csock);

  $pid = pcntl_fork();
  if ($pid == -1) {
    die('子进程创建失败');
  } else if ($pid) {
    $pids[] = $pid;
  } else {
    $redis = new  Redis();
    $redis->connect('127.0.0.1',6379);

    $conOpen = true;    
    while($conOpen) {    
 
        $r = array($csock);
        $w = NULL;
        $e = NULL;
        $t = NULL;
        if(0 < stream_select($r, $w, $e, $t)) {
           foreach($r as $i => $fd) {
              if($fd == $csock) {
                  $text = fgets($csock);
                  if($text == "") {
                       echo "Connection closed by peer\n";
                       $conOpen = false;
                       fclose($csock);
                       break;
                  }
                  echo "\r" .$text;  
               }
           }
       }
    }
    exit(1);
  }
}
foreach ($pids as $key => $value) {
  pcntl_waitpid($value, $status);
}
