#!/usr/local/bin/php
<?php
$name = $argv[1];
if (!$name) {
  die("请告诉我你是谁");
}

echo <<<EOT
		 -----------------
		|       hello     |
		|       world     |
		 -----------------
EOT;
echo "\n";
echo "connecting to the server\n";

$port = 9501;
$address = "127.0.0.1";

$socket = stream_socket_client("tcp://$address:$port"); 
if (!$socket) {
    echo "connection error\n";
    exit(1);
}

echo "connection established\n";
echo "me: ";
$uin = fopen("php://stdin", "r");
$conOpen = true;    
while($conOpen) {    
 
    $r = array($socket, $uin);
    $w = NULL;
    $e = NULL;
    $t = NULL;
    if(0 < stream_select($r, $w, $e, $t)) {
       foreach($r as $i => $fd) {
          if($fd == $uin) {
               $text = fgets($uin);
               echo "me: ";
               fwrite($socket, $name.':'.$text);
           } else {
               $text = fgets($socket);
               if ($text == "") {
                   echo "Connection closed\n";
                   $conOpen = false;
                   fclose($socket);
                   exit(0);
               }
               echo "\r" . $text;
               echo "me: ";
           }
       }
   }
} 
